# Generated by Django 4.1.5 on 2023-01-10 23:47

import autoslug.fields
import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='store/brand/', verbose_name='Marka Fotosu:')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Marka:')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayınlama Tarihi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Marka',
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=store.models.image_upload_to, verbose_name='Kategori Fotosu:')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Kategori:')),
                ('explain', ckeditor.fields.RichTextField(blank=True, verbose_name='Kategori Tanımı:')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayınlama Tarihi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=store.models.image_upload_to, verbose_name='Ürün Fotosu:')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Başlık:')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Açıklama')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('price', models.FloatField(verbose_name='Fiyat')),
                ('update_price', models.FloatField(blank=True, verbose_name='Güncel Fiyat')),
                ('stock', models.IntegerField(verbose_name='stok')),
                ('is_available', models.CharField(choices=[('SY', 'Stokta YOK'), ('SV', 'Stokta VAR')], default='SY', max_length=2, verbose_name='Stock Durumu')),
                ('extra_image1', models.ImageField(blank=True, upload_to=store.models.extra_image_upload_to, verbose_name='Slayt1')),
                ('extra_image2', models.ImageField(blank=True, upload_to=store.models.extra_image_upload_to, verbose_name='Slayt2')),
                ('extra_image3', models.ImageField(blank=True, upload_to=store.models.extra_image_upload_to, verbose_name='Slayt3')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.category', verbose_name='Kategori')),
                ('likes', models.ManyToManyField(blank=True, related_name='product_like', to=settings.AUTH_USER_MODEL, verbose_name='Beğendim')),
                ('whir_list', models.ManyToManyField(blank=True, related_name='ürün_istek', to=settings.AUTH_USER_MODEL, verbose_name='Ürün İstek Listesi')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'db_table': 'product',
                'ordering': ['created'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created'], name='product_created_faa237_idx'),
        ),
    ]
