# Generated by Django 5.1.3 on 2024-12-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='Sipariş tamalandı mı ?'),
        ),
    ]
