# Generated by Django 4.1.6 on 2023-02-05 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(related_name='product_liked', to=settings.AUTH_USER_MODEL, verbose_name='Beğeniler'),
        ),
    ]
