# Generated by Django 5.1.3 on 2024-12-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_cart_cart_id_alter_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default=115903875387520808484438432386123193252, editable=False, max_length=500, unique=True, verbose_name='Sepet İD'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='869443698282', editable=False, max_length=1000, verbose_name='Ürün Kodu'),
        ),
    ]
