# Generated by Django 5.1.3 on 2024-12-21 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_newsletter_is_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='money_symbol',
            field=models.CharField(blank=True, help_text='TL, $, ', max_length=100, null=True, verbose_name='Para birimi'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default=26635401397316811951943178320140266360, editable=False, max_length=500, unique=True, verbose_name='Sepet İD'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='store.productcategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='869443626099', editable=False, max_length=1000, verbose_name='product code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='Product Title:'),
        ),
    ]
