# Generated by Django 5.1.3 on 2024-12-21 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_money_symbol_alter_cart_cart_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default=96220548344158521267864672534820697105, editable=False, max_length=500, unique=True, verbose_name='Sepet İD'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='This is the help text', on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='store.productcategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='869443630593', editable=False, max_length=1000, verbose_name='product code'),
        ),
    ]
