# Generated by Django 5.1.3 on 2024-12-21 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_cart_cart_id_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default=82821127117292643558339709258148394591, editable=False, max_length=500, unique=True, verbose_name='Sepet İD'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='store.productcategory', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='product',
            name='money_symbol',
            field=models.CharField(default='TL', help_text='TL, $, vs...', max_length=100, verbose_name='Para birimi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='869443638663', editable=False, max_length=1000, verbose_name='product code'),
        ),
    ]
