# Generated by Django 4.1.5 on 2023-02-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default=93933704326715248692280447425940688665, max_length=500, verbose_name='Sepet İD'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer',
            field=models.CharField(max_length=100, verbose_name='Müşteri'),
        ),
    ]
