# Generated by Django 4.1.5 on 2023-02-05 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_cart_cart_id_alter_customer_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default=2309497499906400423529210010080819146, max_length=500, verbose_name='Sepet İD'),
        ),
        migrations.AlterField(
            model_name='myfavorite',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_name', to='carts.customer', verbose_name='Müşteri'),
        ),
    ]
