# Generated by Django 4.1.6 on 2023-02-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_alter_cart_cart_id_alter_myfavorite_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default=114542445947680356726622101082943579869, max_length=500, verbose_name='Sepet İD'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer',
            field=models.CharField(max_length=255, verbose_name='Müşteri'),
        ),
    ]
