# Generated by Django 4.1.6 on 2023-02-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_alter_cart_cart_id_alter_customer_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default=180981109187046200652655466053103538126, max_length=500, verbose_name='Sepet İD'),
        ),
    ]
