# Generated by Django 4.1.6 on 2023-02-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Müşteri', 'verbose_name_plural': 'Müşteri'},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer',
            new_name='customer_name',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default=265371135049361743325616588019762608388, max_length=500, verbose_name='Sepet İD'),
        ),
    ]
