# Generated by Django 4.1.6 on 2023-02-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default=137387876515471278363242425331639319835, max_length=500, verbose_name='Sepet İD'),
        ),
    ]
