# Generated by Django 4.1.6 on 2023-02-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_alter_cart_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myfavorite',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='myfavorite',
            name='product',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default=53545561261714009516171147825363121881, max_length=500, verbose_name='Sepet İD'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='MyFavorite',
        ),
    ]
