# Generated by Django 5.1.3 on 2024-12-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingmodels',
            name='google_map',
            field=models.TextField(blank=True, help_text='Google Haritadaki iframe bağlantısı', null=True, verbose_name='Google Haritadaki Konumunuz'),
        ),
    ]
