# Generated by Django 5.1.3 on 2024-12-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_sitesettingmodels_google_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettingmodels',
            name='google_map',
            field=models.CharField(blank=True, help_text='Google Haritadaki iframe bağlantısı', max_length=1000, null=True, verbose_name='Google Haritadaki Konumunuz'),
        ),
    ]
