# Generated by Django 5.1.3 on 2024-12-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_sitesettingmodels_google_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettingmodels',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettingmodels',
            name='explain',
            field=models.TextField(help_text='Kısaca nasıl bir site biraz bahsedin...', verbose_name='Site Açıklaması'),
        ),
        migrations.AlterField(
            model_name='sitesettingmodels',
            name='google_map',
            field=models.TextField(blank=True, help_text='Google Haritadaki iframe bağlantısı', null=True, verbose_name='Google Haritadaki Konumunuz'),
        ),
        migrations.AlterField(
            model_name='sitesettingmodels',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Site Adı'),
        ),
        migrations.AlterField(
            model_name='sitesettingmodels',
            name='theme',
            field=models.CharField(choices=[('neumorphism', 'Neumorphism')], max_length=100, verbose_name='Site Teması'),
        ),
    ]
